[project]
name = "wr"
version = "0.1.0"
description = "A Wild Rift Knowledge and Training Ecosystem"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.9.10",
]
